

server:
  port: 3002

spring:
  application:
    name: hystrix_cinsume


eureka:
  instance:
    prefer-ip-address: true
    instance-id: hystrix_cinsume
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: ['hystrix.stream','info','health']
hystrix:
  dashboard:
    enable-ignore-connection-close-header: true
    proxy-stream-allow-list: localhost